# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.CharField(max_length=120, unique=True)),
                ('oper', models.CharField(max_length=120, null=True)),
                ('parent_type', models.CharField(max_length=20, null=True)),
                ('i_class', models.CharField(default='fa fa-laptop', max_length=20)),
                ('note', models.CharField(default='无', max_length=120, null=True)),
            ],
        ),
    ]
