# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='oper',
        ),
        migrations.AlterField(
            model_name='permission',
            name='i_class',
            field=models.CharField(default='fa fa-laptop', max_length=20, verbose_name='Css'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='note',
            field=models.CharField(default='无', max_length=120, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='parent_type',
            field=models.CharField(max_length=20, null=True, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=120, unique=True, verbose_name='链接'),
        ),
    ]
