# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0003_auto_20180105_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('data_joined', models.DateTimeField(null=True)),
                ('usergroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.UserGroup')),
            ],
        ),
    ]
