# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0005_auto_20180105_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_joined',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='加入日期'),
        ),
    ]
