# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_auto_20180105_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256, verbose_name='Url')),
                ('log_datetime', models.DateTimeField(verbose_name='记录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.User', verbose_name='用户')),
            ],
        ),
    ]
